const allRoles = {
  user: ['changePassword', 'canImmobilize', 'getTrackingData', 'sendCommand',
    'getAlerts', 'manageUserAlerts', 'getUserAlerts',],
  admin: ['getUsers', 'manageUsers', 'changePassword', 'canImmobilize',
    'getAlerts', 'getTrackingData', 'sendCommand', 'manageUserAlerts', 'getUserAlerts',],
  reseller: [
    'getUsers',
    'manageUsers',
    'changePassword',
    'getClients',
    'manageClients',
    'canImmobilize',
    'manageDevices',
    'getDevices',
    'getModels',
    'getSensors',
    'manageUserAlerts',
    'getUserAlerts',
    'getAlerts',
    'manageObjects',
    'getObjects',
    'getTrackingData',
    'sendCommand',
  ],
  superadmin: [
    'getUsers',
    'manageUsers',
    'changePassword',
    'getClients',
    'manageClients',
    'canImmobilize',
    'manageDevices',
    'getDevices',
    'manageModels',
    'getModels',
    'manageSensors',
    'getSensors',
    'manageAlerts',
    'getAlerts',
    'manageUserAlerts',
    'getUserAlerts',
    'manageObjects',
    'getObjects',
    'getTrackingData',
    'sendCommand',
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
